version: '3.7'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/srv/www
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  app:
    image: php:7.3-fpm
    volumes:
      - ./src:/srv/www
    working_dir: /srv/www